spring:  
  application:
    name: zkui
  main:
    show-banner: false
  http:
    multipart:
      maxFileSize: 2Mb
    maxRequestSize: 2Mb
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    allow-request-override: true
    expose-session-attributes: true
    allow-session-override: true
    request-context-attribute: request
    suffix: .ftl.html
server:
  port: 8081
  context-path: /
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8
zookeeper:
  clientUrls: localhost:2181,localhost:2182,localhost:2183
  sessionTimeout: 300
  defaultAcl: 
  scmRepo: 
  scmRepoPath: 
system: 
  ldapAuth: false #if set to true then userSet is used for authentication, else ldap authentication is used.
  ldapDomain: mycompany,mydomain
  ldapUrl: ldap://127.0.0.1:9090/dc=mycom,dc=com #ldap authentication url. Ignore if using file based authentication.
  ldapRoleSet: '{"users": [{ "username":"domain\\user1" , "role": "ADMIN" }]}' #Specific roles for ldap authenticated users. Ignore if using file based authentication.
  userSet :  '{"users": [{ "username":"admin" , "password":"admin","role": "ADMIN" },{ "username":"appconfig" , "password":"appconfig","role": "USER" }]}'
